// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetClips() {
  return window['go']['main']['App']['GetClips']();
}

export function LoadClipsFromDB() {
  return window['go']['main']['App']['LoadClipsFromDB']();
}
