// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {helix} from '../models';

export function GetClips():Promise<string>;

export function LoadClipsFromDB():Promise<Array<helix.Clip>>;
